name: flipperkit_http_interceptor
description: flipperkit_http_interceptor
version: 0.0.3
author: sengerts
homepage: https://github.com/leanflutter/flutter_flipperkit_plugins

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_flipperkit: ^0.0.28
  http: ^0.13.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter